name: metrix demo
on: push
jobs:
  buildjob:
    continue-on-error: true
    strategy:
      matrix:
       os-name: [ubuntu-latest,windows-latest]
       javav: [8]
       exclude:
       - os-name: ubuntu-latest
         javav: 8
       include:
       - os-name: ubuntu-latest
         javav: 21
        
    runs-on: ${{matrix.os-name}}
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: ${{matrix.javav}}
      - name: maven build
        run: mvn clean test
    