name: mywf
on:
   workflow_dispatch:
   push:
    branches:
     - main
    paths:
     - '**.yml'
   pull_request:
     types: [opened, reopened]
     branches: [main,R1]
        
jobs:
  Testjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin' 
            java-version: '8'
      - name: mvn test step
        run: mvn clean test
        
        
  Buildjob:
    needs: Testjob
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: set up java
       uses: actions/setup-java@v4
       with:
            distribution: 'temurin' 
            java-version: '8'
     - name: build
       run: mvn clean package -Dmaven.test.skip 