name: mywf
on:
   workflow_dispatch:
   push:
    branches:
     - main
    paths:
     - '**.yml'
   pull_request:
     types: [opened, reopened]
     branches: [main,R1]
env:
  MyName: Utkarsh    ##wf level env variable
  password: ${{secrets.password}}   ##repository level secret
jobs:
  Testjob:
   runs-on: ubuntu-latest
   env:
       yourName: shyam   ##job level env variable
       java_version: 8
    
   steps:
      - name: checkout
        uses: actions/checkout@v4 
      - name: set up java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin' 
            java-version: ${{env.java_version}} ##must be accessed using context object
      - name: cache maven dependncies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
             ${{ runner.os }}-maven-
      - name: mvn test step
        id: teststepid
        run: mvn clean test
      - name: print env variable2
        env:
              hi: ramu  ##step level env variable
        if: "{{steps.teststepid.outcome == 'failure'}}"
        run:  |
         echo "my name is $MyName $hi"
         echo " job level name ${{ env.yourName}}"
         echo "password is: ${{env.password}}"
         echo "password is: $password"
      
        
  Buildjob:
    #needs: Testjob
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: set up java
       uses: actions/setup-java@v4
       with:
            distribution: 'temurin' 
            java-version: '8'
     - name: cache maven dependncies
       uses: actions/cache@v4
       with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
             ${{ runner.os }}-maven-
     - name: build
       run: mvn clean package -Dmaven.test.skip
       
     - name: upload artifact
       uses: actions/upload-artifact@v4
       with:
           name: my-artifact
           path: target/*.jar
     - name: print env variable2
       run:  echo "my name is $MyName"  
           
  Deployjob:
   needs: Buildjob
   runs-on: ubuntu-latest
   steps:
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: show files
      run: ls   
    - name: deploy job
      run: echo "deploying"
    - name: print env variable3
      run:  echo "my name is $MyName"
    - name: print env variable3 using context
      run:  |
       echo "my name is ${{ env.MyName}}"
       echo " job level name ${{ env.yourName}}"
      
     