name: mywf
on:
   workflow_dispatch:
   push:
    branches:
     - main
    paths:
     - '**.yml'
   pull_request:
     types: [opened, reopened]
     branches: [main,R1]
env:
  MyName: Utkarsh       
jobs:
  Testjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin' 
            java-version: '8'
      - name: cache maven dependncies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
             ${{ runner.os }}-maven-
      - name: mvn test step
        run: mvn clean test
      - name: print env variable2
        run:  echo "my name is $MyName"
        
        
  Buildjob:
    needs: Testjob
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: set up java
       uses: actions/setup-java@v4
       with:
            distribution: 'temurin' 
            java-version: '8'
     - name: cache maven dependncies
       uses: actions/cache@v4
       with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
             ${{ runner.os }}-maven-
     - name: build
       run: mvn clean package -Dmaven.test.skip
       
     - name: upload artifact
       uses: actions/upload-artifact@v4
       with:
           name: my-artifact
           path: target/*.jar
     - name: print env variable2
       run:  echo "my name is $MyName"  
           
  Deployjob:
   needs: Buildjob
   runs-on: ubuntu-latest
   steps:
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: show files
      run: ls   
    - name: deploy job
      run: echo "deploying"
    - name: print env variable3
      run:  echo "my name is $MyName"
     